package pistonmc.forge1710template;

// This file is automatically generated
// Do not edit this file manually

public interface ModInfo {
    String Id = "forge1710template";
    String Version = "1.0.0";
    String Group = "pistonmc.forge1710template";
    String GroupInternal = "pistonmc/forge1710template";
}

